name: Alerta de PRs no Discord

on:
  schedule:
    - cron: '30 12 * * *' # Todos os dias às 08:30 da manhã (Fuso UTC-4 / Cuiabá)
  workflow_dispatch: # Botão de rodar manualmente

permissions:
  pull-requests: read
  contents: read

jobs:
  notificar-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar código do repositório
        uses: actions/checkout@v4

      - name: Buscar PRs e Preparar Mensagem
        id: buscar_prs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Busca os PRs e formata 
          gh pr list --state open --limit 50 --json number,title,url,reviewRequests --jq '.[] | select((.reviewRequests | length) <= 1) | "- [#\(.number)](\(.url)) \(.title) *(Revisores: \(.reviewRequests | length))*"' > lista.txt

          # Valida se o arquivo está vazio. Se estiver, interrompe o job aqui sem enviar o alerta.
          if [ ! -s lista.txt ]; then
            echo "Nenhum PR sem revisor encontrado. Encerrando sem enviar notificação."
            echo "enviar_alerta=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Se chegou aqui, existem PRs. Cria o cabeçalho e junta com a lista.
          echo -e "**Alerta: PRs abertos aguardando revisores:**\n" > mensagem.txt
          cat lista.txt >> mensagem.txt
          echo "enviar_alerta=true" >> $GITHUB_OUTPUT

      - name: Enviar para o Discord
        # Esta condição garante que o passo só roda se o passo anterior definir 'enviar_alerta' como true
        if: steps.buscar_prs.outputs.enviar_alerta == 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Empacota a mensagem em JSON de forma segura 
          jq -n --arg msg "$(cat mensagem.txt)" '{content: $msg}' > payload.json
          
          # Dispara para o Webhook do Discord
          curl -H "Content-Type: application/json" -X POST -d @payload.json "$DISCORD_WEBHOOK"